- id: '1647740106539'
  alias: Bathroom Blind Open
  description: ''
  trigger:
  - device_id: 4a98b9f07ae8642eba501ae157dcaff0
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: open
  condition: []
  action:
  - device_id: 4658ba1850b0e1ef12c15401c314e5b7
    domain: cover
    entity_id: cover.ikea_blind_window_covering
    type: set_position
    position: 60
  mode: single
- id: '1647740156956'
  alias: Bathroom Blind Close
  description: ''
  trigger:
  - device_id: 4a98b9f07ae8642eba501ae157dcaff0
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: close
  condition: []
  action:
  - device_id: 4658ba1850b0e1ef12c15401c314e5b7
    domain: cover
    entity_id: cover.ikea_blind_window_covering
    type: set_position
    position: 0
  mode: single
- id: '1647740574417'
  alias: Hutch Lights On/Off
  description: ''
  trigger:
  - device_id: bd9102b8a2141ab0d813a56c9dd25420
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
  condition: []
  action:
  - type: toggle
    device_id: e5c2bc150613013fc017fdec4e88859d
    entity_id: switch.ikea_living_ac_on_off
    domain: switch
  mode: single
- id: '1647823096364'
  alias: Master 1 Ceiling
  description: ''
  trigger:
  - device_id: 87808d9472f83f59a678dcd45bb29f31
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: 5f06e956-291d-4fef-a963-b0ab91efaa2d
  condition: []
  action:
  - service: light.toggle
    data:
      transition: 2
      brightness_pct: 70
      color_temp: 260
    target:
      entity_id: light.master_ceiling
  mode: single
- id: '1647824029868'
  alias: Master 2 Lamp
  description: ''
  trigger:
  - device_id: 87808d9472f83f59a678dcd45bb29f31
    domain: hue
    platform: device
    type: initial_press
    subtype: 2
    unique_id: aef93b0c-f731-415f-9d54-1233ed8fff22
  condition: []
  action:
  - service: light.toggle
    data:
      transition: 2
      brightness_pct: 70
      color_temp: 260
    target:
      device_id: 6189f32d54b166d80ec653bcea9ff4f5
  mode: single
- id: '1647824251067'
  alias: Master 3 AC
  description: ''
  trigger:
  - device_id: 87808d9472f83f59a678dcd45bb29f31
    domain: hue
    platform: device
    type: initial_press
    subtype: 3
    unique_id: 21bf4ade-71a4-4840-b167-3cb2b035f19b
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      device_id: 4b50a6602eb6c7028efa4cb978108c3f
  mode: single
- id: '1647830747131'
  alias: Basement On
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 8daec42923257db4e4e5a29d17ab1806
    entity_id: switch.basement_tp_switch
    domain: switch
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.basement_all
    metadata: {}
  mode: single
- id: '1647830838415'
  alias: Basement Off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 8daec42923257db4e4e5a29d17ab1806
    entity_id: switch.basement_tp_switch
    domain: switch
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      device_id:
      - e2c57d7a1f2dd7dff2280769680471db
      - d532c6e5e10cec4981bc8bfc84195495
      - 73154c5d5c1a8394de2dcf01b7f0ff3b
      - a27b742da5f12feb52cb4b654196ea17
  mode: single
- id: '1647831192671'
  alias: Shelf Lights Off
  description: ''
  trigger:
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id:
      - b355515cc044c8fef8a5d3b3a0c258e9
      - 040e6ba9db6310489074e48dd7ec3fbb
  mode: single
- id: '1647832095897'
  alias: Master 4 Off
  description: ''
  trigger:
  - device_id: 87808d9472f83f59a678dcd45bb29f31
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    unique_id: cb3da41d-d11d-4060-972d-c97273c35fec
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id: 4b50a6602eb6c7028efa4cb978108c3f
  - service: light.turn_off
    data: {}
    target:
      device_id: 6189f32d54b166d80ec653bcea9ff4f5
      entity_id: light.master_ceiling
  mode: single
- id: '1647993437383'
  alias: Outside Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '- 00:15:00'
  condition: []
  action:
  - type: turn_on
    device_id: 2778b11d88904a5e08d9e34990824eec
    entity_id: light.hue_porch_ceiling
    domain: light
    brightness_pct: 15
  - type: turn_on
    device_id: d3c69e67c842f4c26c42d6e1255e13b2
    entity_id: switch.deck_cafe_lights
    domain: switch
  mode: single
- id: '1647994807482'
  alias: Shelves and Cabinets
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      device_id:
      - b355515cc044c8fef8a5d3b3a0c258e9
      - 696d8752afd5852d9bf79d97bfcf626d
      - 040e6ba9db6310489074e48dd7ec3fbb
  mode: single
- id: '1647994901395'
  alias: Shelves Off
  description: ''
  trigger:
  - platform: time
    at: 04:30:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      device_id:
      - b355515cc044c8fef8a5d3b3a0c258e9
      - 040e6ba9db6310489074e48dd7ec3fbb
  mode: single
- id: '1647995027069'
  alias: Outside Lights Off
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: 2778b11d88904a5e08d9e34990824eec
    entity_id: light.hue_porch_ceiling
    domain: light
  - type: turn_off
    device_id: d3c69e67c842f4c26c42d6e1255e13b2
    entity_id: switch.deck_cafe_lights
    domain: switch
  mode: single
- id: '1648134976799'
  alias: Kitchen Cabinets Off
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - type: turn_off
    device_id: 696d8752afd5852d9bf79d97bfcf626d
    entity_id: switch.kitchen_cabinets
    domain: switch
  mode: single
- id: '1648166737081'
  alias: Kids Closet On
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779ded23
    to: 'on'
  condition: []
  action:
  - type: turn_on
    device_id: eb1367b64dfc8fc0dbc4dcd6a701decd
    entity_id: light.hue_kids_closet
    domain: light
    brightness_pct: 100
  mode: single
- id: '1648167231002'
  alias: Kids Closet Off
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzesense_779ded23
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 3
  condition: []
  action:
  - type: turn_off
    device_id: eb1367b64dfc8fc0dbc4dcd6a701decd
    entity_id: light.hue_kids_closet
    domain: light
  mode: single
- id: '1648175655645'
  alias: Stairs Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 98f29d65ca15075681da1ac9dbf3f85d
    entity_id: binary_sensor.hue_stairs_motion_motion
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
    after_offset: -00:10:00
  action:
  - type: turn_on
    device_id: 02522e0509104c229d8fb9005d09ebfb
    entity_id: light.hue_filament
    domain: light
    brightness_pct: 10
  - service: light.turn_on
    data:
      color_temp: 240
      brightness_pct: 25
    target:
      entity_id: light.stairs_spots
  mode: single
- id: '1648233937569'
  alias: Stairs Off
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 98f29d65ca15075681da1ac9dbf3f85d
    entity_id: binary_sensor.hue_stairs_motion_motion
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 45
  condition:
  - condition: device
    type: is_on
    device_id: 02522e0509104c229d8fb9005d09ebfb
    entity_id: light.hue_filament
    domain: light
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: light.stairs_spots
        state: 'on'
  action:
  - service: light.turn_off
    data: {}
    target:
      device_id: 02522e0509104c229d8fb9005d09ebfb
      entity_id: light.stairs_spots
  mode: single
- id: '1648517951051'
  alias: Ikea Remote Kitchen
  description: ''
  trigger:
  - device_id: bd9102b8a2141ab0d813a56c9dd25420
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: left
  condition: []
  action:
  - type: toggle
    device_id: a3f7f3f514da6a215b9280b1e22dd001
    entity_id: light.hue_kitchen_ceiling
    domain: light
  mode: single
- id: '1649128160763'
  alias: GitHub HA Backup
  description: ''
  trigger:
  - platform: time
    at: '23:45:00'
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954-ssh
      input: /config/ha_gitpush.sh
  mode: single
- id: '1649469926628'
  alias: Living Hue Strip Off
  description: ''
  trigger:
  - platform: time
    at: 00:30:00
  condition: []
  action:
  - type: turn_off
    device_id: 22c92ce079bdfd628e4c0543dda847f9
    entity_id: light.hue_lightstrip
    domain: light
  mode: single
- id: '1649470251797'
  alias: Living Hue Strip On
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '- 00:10:00'
  condition: []
  action:
  - type: turn_on
    device_id: 22c92ce079bdfd628e4c0543dda847f9
    entity_id: light.hue_lightstrip
    domain: light
    brightness_pct: 15
  mode: single
- id: '1649533585709'
  alias: Bathroom Blinds Morning
  description: ''
  trigger:
  - platform: time
    at: 05:45:00
  condition: []
  action:
  - device_id: 4658ba1850b0e1ef12c15401c314e5b7
    domain: cover
    entity_id: cover.ikea_blind_window_covering
    type: set_position
    position: 60
  mode: single
- id: '1649533638208'
  alias: Bathroom Blinds Night
  description: ''
  trigger:
  - platform: time
    at: '19:30:00'
  condition: []
  action:
  - device_id: 4658ba1850b0e1ef12c15401c314e5b7
    domain: cover
    entity_id: cover.ikea_blind_window_covering
    type: set_position
    position: 0
  mode: single
- id: '1649996251633'
  alias: Reset Lock Auto
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: input_text.keymaster_yale_front_autolock_door_time_day
    state: 00:15:00
  action:
  - service: input_text.set_value
    data:
      value: 00:02:00
    target:
      entity_id: input_text.keymaster_yale_front_autolock_door_time_day
  mode: single
- id: '1650772882480'
  alias: Set Yale Status
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 780bd205bed96d943c01db65ab108df8
    entity_id: binary_sensor.smartthings_front_ias_zone
    domain: binary_sensor
  condition: []
  action:
  - event: ''
    event_data: {}
  mode: single
- id: '1653526742468'
  alias: Living Fans Off
  description: ''
  trigger:
  - platform: time
    at: 07:10:00
  condition:
  - condition: time
    before: 08:00:00
    after: 07:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - device_id: 4091b1e5500f4baa73a43f1383679145
    domain: fan
    entity_id: fan.wyze_shelf_fan
    type: turn_off
  - device_id: d38ec57754412930d56968d2a71ea8c5
    domain: fan
    entity_id: fan.wyze_window_fan
    type: turn_off
  mode: single
- id: '1653697588822'
  alias: Kids AC Control
  description: ''
  trigger:
  - device_id: b876525c719bdbcf93e3da2da4c5eb2d
    domain: zha
    platform: device
    type: device_rotated
    subtype: right
  - device_id: b876525c719bdbcf93e3da2da4c5eb2d
    domain: zha
    platform: device
    type: device_rotated
    subtype: left
  condition: []
  action:
  - type: toggle
    device_id: d45270a0c02aa136c7fba7b5085952df
    entity_id: switch.ikea_kids_ac_on_off
    domain: switch
  mode: single
- id: '1657157286786'
  alias: Pool Pump On
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 47c9e7ee00cdbbd2cf7c6b16d4800121
    entity_id: switch.pool_pump
    domain: switch
  mode: single
- id: '1657157402153'
  alias: Pool Pump Off
  description: ''
  trigger:
  - platform: time
    at: '12:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 47c9e7ee00cdbbd2cf7c6b16d4800121
    entity_id: switch.pool_pump
    domain: switch
  mode: single
