- platform: influxdb
  host: a0d7b954-influxdb
  port: 8086
  username: !secret mariadb_user
  password: !secret mariadb_pass
  queries:
    - name: InfluxDB Database Size
      unit_of_measurement: MB
      value_template: '{{ (value | float / 1024 /1024) | round(1) }}'
      group_function: mean
      measurement: '"monitor"."shard"'
      database: _internal
      where: 'time > now() - 1m AND "database"=''homeassistant'''
      field: diskBytes 
      